{{- range $comp, $values := .Values.windmill -}}
{{- if typeIs "map[string]interface {}" $values }}
{{- with $values.autoscaling -}}
{{- if .enabled }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ $.Release.Namespace }}
  name: windmill-{{ $comp }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: windmill-{{ $comp }}
  minReplicas: {{ $values.replicas | default (index $.Values.windmill (printf "%sReplicas" $comp)) | default 1 }}
  maxReplicas: {{ $values.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ $values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}